export enum PartnerCenterMenu {
  MONTHLY_PARKING_USER_LIST = "MONTHLY_PARKING_USER_LIST",
  MONTHLY_PARKING_REQUEST_LIST = "MONTHLY_PARKING_REQUEST_LIST",
  MONTHLY_PARKING_REQUEST_WRITE = "MONTHLY_PARKING_REQUEST_WRITE",
  MONTHLY_PARKING_EXTEND_REQUEST_WRITE = "MONTHLY_PARKING_EXTEND_REQUEST_WRITE",
  PAYMENT_LIST = "PAYMENT_LIST",
  PAYMENT_DETAIL = "PAYMENT_DETAIL",
  PARTNER_DETAIL = "PARTNER_DETAIL",
  PARTNER_MEMBER_LIST = "PARTNER_MEMBER_LIST",
  USER_PROFILE = "USER_PROFILE",
}

export enum SettlementReportRouteName {
  SIGN_IN = "SettlementUserAuthorization",
  REPORT = "SettlementReport",
  BLANK = "SettlementReportBlank",
}

export enum PartnerCenterPermission {
  PROFILE_VIEW = "PROFILE_VIEW",
  PROFILE_UPDATE = "PROFILE_UPDATE",
  TICKET_REQUEST_LIST = "TICKET_REQUEST_LIST",
  TICKET_REQUEST_VIEW = "TICKET_REQUEST_VIEW",
  TICKET_REQUEST_CREATE = "TICKET_REQUEST_CREATE",
  TICKET_LIST = "TICKET_LIST",
  TICKET_UPDATE = "TICKET_UPDATE",
  PAYMENT_LIST = "PAYMENT_LIST",
  PAYMENT_VIEW = "PAYMENT_VIEW",
  PARTNER_VIEW = "PARTNER_VIEW",
  MEMBER_LIST = "MEMBER_LIST",
  CARD_CREATE = "CARD_CREATE",
  TICKET_CONTRACT_LIST = "TICKET_CONTRACT_LIST",
}

export enum MonthlyParkingCreatorTypeCode {
  PARTNER_USER = 100,
  ADMIN = 200,
  SYSTEM = 300,
}

export enum MonthlyParkingRequestTypeCode {
  NEW = 100,
  EXTEND = 110,
  CHANGE_CAR = 200,
  CHANGE_USER = 210,
  STOP = 310,
}
export enum MonthlyParkingRequestStatusCode {
  WAIT = 100,
  RECEIVE = 150,
  SEND = 160,
  ALLOW = 200,
  DENY = 210,
  CANCEL = 220,
}

export enum MonthlyParkingUseStatusCode {
  WAIT = 100,
  USING = 200,
  END = 300,
}
